import mongoose from 'mongoose';
import Job from '../models/Job.js';
import User from '../models/User.js';
import dotenv from 'dotenv';

dotenv.config();

const seed100Jobs = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    
    let systemUser = await User.findOne({ email: 'system@jobportal.com' });
    if (!systemUser) {
      systemUser = new User({
        name: 'Job Portal System',
        email: 'system@jobportal.com',
        password: 'system123',
        role: 'employer',
        companyName: 'Job Portal'
      });
      await systemUser.save();
    }

    const jobs = [
      // Technology Jobs (40 jobs)
      { title: 'Senior Full Stack Developer', description: 'Build scalable web applications using React and Node.js', location: 'San Francisco, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 140000, max: 180000 }, requirements: ['5+ years experience', 'React', 'Node.js', 'MongoDB'] },
      { title: 'Frontend React Developer', description: 'Create responsive user interfaces with React and TypeScript', location: 'New York, NY', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 100000, max: 130000 }, requirements: ['3+ years React', 'TypeScript', 'CSS3', 'Git'] },
      { title: 'Backend Python Developer', description: 'Develop APIs and microservices using Python and Django', location: 'Austin, TX', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 110000, max: 140000 }, requirements: ['Python', 'Django', 'PostgreSQL', 'Docker'] },
      { title: 'DevOps Engineer', description: 'Manage cloud infrastructure and CI/CD pipelines', location: 'Seattle, WA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 130000, max: 170000 }, requirements: ['AWS', 'Kubernetes', 'Jenkins', 'Terraform'] },
      { title: 'Data Scientist', description: 'Analyze large datasets and build ML models', location: 'Remote', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 125000, max: 165000 }, requirements: ['Python', 'Machine Learning', 'SQL', 'Statistics'] },
      { title: 'Mobile App Developer', description: 'Build native iOS and Android applications', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 105000, max: 135000 }, requirements: ['Swift', 'Kotlin', 'React Native', 'Mobile UI/UX'] },
      { title: 'Cloud Architect', description: 'Design and implement cloud solutions', location: 'Chicago, IL', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 150000, max: 190000 }, requirements: ['AWS/Azure', 'Microservices', 'System Design', '7+ years experience'] },
      { title: 'QA Automation Engineer', description: 'Develop automated testing frameworks', location: 'Boston, MA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 85000, max: 115000 }, requirements: ['Selenium', 'Java', 'Test Automation', 'Agile'] },
      { title: 'Cybersecurity Analyst', description: 'Monitor and protect against security threats', location: 'Washington, DC', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 95000, max: 125000 }, requirements: ['Security Tools', 'Network Security', 'Incident Response', 'CISSP'] },
      { title: 'UI/UX Designer', description: 'Design intuitive user interfaces and experiences', location: 'San Diego, CA', jobType: 'full-time', category: 'Design', experienceLevel: 'mid', salary: { min: 80000, max: 110000 }, requirements: ['Figma', 'Adobe Creative Suite', 'User Research', 'Prototyping'] },
      { title: 'Machine Learning Engineer', description: 'Deploy ML models into production systems', location: 'Mountain View, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 145000, max: 185000 }, requirements: ['TensorFlow', 'PyTorch', 'MLOps', 'Python'] },
      { title: 'Database Administrator', description: 'Manage and optimize database systems', location: 'Dallas, TX', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 90000, max: 120000 }, requirements: ['SQL Server', 'MySQL', 'Performance Tuning', 'Backup/Recovery'] },
      { title: 'Software Engineering Intern', description: 'Learn software development in a team environment', location: 'Palo Alto, CA', jobType: 'internship', category: 'Technology', experienceLevel: 'entry', salary: { min: 25, max: 35 }, requirements: ['Computer Science Student', 'Programming Basics', 'Git', 'Problem Solving'] },
      { title: 'Product Manager', description: 'Lead product strategy and development', location: 'San Francisco, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 135000, max: 175000 }, requirements: ['Product Strategy', 'Agile', 'Analytics', 'Leadership'] },
      { title: 'Site Reliability Engineer', description: 'Ensure system reliability and performance', location: 'Remote', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 140000, max: 180000 }, requirements: ['Linux', 'Monitoring', 'Automation', 'Incident Management'] },
      { title: 'Blockchain Developer', description: 'Build decentralized applications and smart contracts', location: 'Miami, FL', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 120000, max: 160000 }, requirements: ['Solidity', 'Web3', 'Ethereum', 'Smart Contracts'] },
      { title: 'Game Developer', description: 'Create engaging video games and interactive experiences', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 95000, max: 125000 }, requirements: ['Unity', 'C#', 'Game Design', '3D Graphics'] },
      { title: 'Technical Writer', description: 'Create technical documentation and user guides', location: 'Remote', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 70000, max: 95000 }, requirements: ['Technical Writing', 'Documentation Tools', 'API Documentation', 'Communication'] },
      { title: 'Systems Administrator', description: 'Maintain and configure server infrastructure', location: 'Phoenix, AZ', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 75000, max: 100000 }, requirements: ['Linux/Windows Server', 'Networking', 'Virtualization', 'Scripting'] },
      { title: 'AI Research Scientist', description: 'Research and develop artificial intelligence algorithms', location: 'Stanford, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 160000, max: 220000 }, requirements: ['PhD in AI/ML', 'Research Experience', 'Deep Learning', 'Publications'] },
      { title: 'Frontend Vue.js Developer', description: 'Build modern web applications using Vue.js', location: 'Portland, OR', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 95000, max: 125000 }, requirements: ['Vue.js', 'JavaScript', 'CSS3', 'Vuex'] },
      { title: 'Backend Java Developer', description: 'Develop enterprise applications using Java Spring', location: 'Atlanta, GA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 100000, max: 130000 }, requirements: ['Java', 'Spring Boot', 'Microservices', 'REST APIs'] },
      { title: 'Network Engineer', description: 'Design and maintain network infrastructure', location: 'Denver, CO', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 85000, max: 115000 }, requirements: ['Cisco', 'Network Protocols', 'Routing/Switching', 'Network Security'] },
      { title: 'Embedded Systems Engineer', description: 'Develop firmware for embedded devices', location: 'San Jose, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 125000, max: 155000 }, requirements: ['C/C++', 'Embedded Systems', 'Hardware', 'Real-time Systems'] },
      { title: 'Data Engineer', description: 'Build and maintain data pipelines and warehouses', location: 'New York, NY', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 115000, max: 145000 }, requirements: ['Python', 'SQL', 'ETL', 'Big Data Tools'] },
      { title: 'Scrum Master', description: 'Facilitate agile development processes', location: 'Remote', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 90000, max: 120000 }, requirements: ['Scrum Certification', 'Agile Methodologies', 'Team Leadership', 'Project Management'] },
      { title: 'Business Intelligence Analyst', description: 'Analyze business data and create reports', location: 'Minneapolis, MN', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 80000, max: 105000 }, requirements: ['SQL', 'Tableau', 'Power BI', 'Data Analysis'] },
      { title: 'Information Security Manager', description: 'Lead cybersecurity initiatives and policies', location: 'Houston, TX', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 130000, max: 165000 }, requirements: ['Security Management', 'Risk Assessment', 'Compliance', 'Team Leadership'] },
      { title: 'Software Architect', description: 'Design high-level software system architecture', location: 'San Francisco, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 155000, max: 195000 }, requirements: ['System Design', 'Architecture Patterns', '10+ years experience', 'Technical Leadership'] },
      { title: 'Junior Web Developer', description: 'Learn web development with HTML, CSS, and JavaScript', location: 'Remote', jobType: 'full-time', category: 'Technology', experienceLevel: 'entry', salary: { min: 55000, max: 75000 }, requirements: ['HTML/CSS', 'JavaScript', 'Git', 'Willingness to Learn'] },
      { title: 'Cloud Security Engineer', description: 'Secure cloud infrastructure and applications', location: 'Arlington, VA', jobType: 'full-time', category: 'Technology', experienceLevel: 'senior', salary: { min: 135000, max: 170000 }, requirements: ['Cloud Security', 'AWS/Azure', 'Security Tools', 'Compliance'] },
      { title: 'React Native Developer', description: 'Build cross-platform mobile applications', location: 'Nashville, TN', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 100000, max: 130000 }, requirements: ['React Native', 'JavaScript', 'Mobile Development', 'Redux'] },
      { title: 'Database Developer', description: 'Design and optimize database schemas and queries', location: 'Tampa, FL', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 85000, max: 110000 }, requirements: ['SQL', 'Database Design', 'Stored Procedures', 'Performance Optimization'] },
      { title: 'IT Support Specialist', description: 'Provide technical support to end users', location: 'Columbus, OH', jobType: 'full-time', category: 'Technology', experienceLevel: 'entry', salary: { min: 45000, max: 60000 }, requirements: ['Technical Support', 'Windows/Mac', 'Troubleshooting', 'Customer Service'] },
      { title: 'Salesforce Developer', description: 'Customize and develop Salesforce applications', location: 'Indianapolis, IN', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 95000, max: 125000 }, requirements: ['Salesforce', 'Apex', 'Lightning', 'Salesforce Certification'] },
      { title: 'Angular Developer', description: 'Build enterprise web applications with Angular', location: 'Charlotte, NC', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 90000, max: 120000 }, requirements: ['Angular', 'TypeScript', 'RxJS', 'NgRx'] },
      { title: 'WordPress Developer', description: 'Create custom WordPress themes and plugins', location: 'Remote', jobType: 'part-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 30, max: 50 }, requirements: ['WordPress', 'PHP', 'MySQL', 'Custom Themes'] },
      { title: 'ETL Developer', description: 'Design and implement data extraction and transformation processes', location: 'Detroit, MI', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 85000, max: 115000 }, requirements: ['ETL Tools', 'SQL', 'Data Warehousing', 'SSIS'] },
      { title: 'iOS Developer', description: 'Develop native iOS applications using Swift', location: 'San Francisco, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 110000, max: 140000 }, requirements: ['Swift', 'iOS SDK', 'Xcode', 'App Store'] },
      { title: 'Android Developer', description: 'Build native Android applications with Kotlin', location: 'Mountain View, CA', jobType: 'full-time', category: 'Technology', experienceLevel: 'mid', salary: { min: 105000, max: 135000 }, requirements: ['Kotlin', 'Android SDK', 'Android Studio', 'Google Play'] },

      // Marketing Jobs (15 jobs)
      { title: 'Digital Marketing Manager', description: 'Lead digital marketing campaigns and strategy', location: 'New York, NY', jobType: 'full-time', category: 'Marketing', experienceLevel: 'senior', salary: { min: 85000, max: 115000 }, requirements: ['Digital Marketing', 'Google Ads', 'SEO/SEM', 'Analytics'] },
      { title: 'Content Marketing Specialist', description: 'Create engaging content for various marketing channels', location: 'Remote', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 60000, max: 80000 }, requirements: ['Content Creation', 'SEO', 'Social Media', 'Writing Skills'] },
      { title: 'Social Media Manager', description: 'Manage social media presence and engagement', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 55000, max: 75000 }, requirements: ['Social Media Platforms', 'Content Strategy', 'Analytics', 'Community Management'] },
      { title: 'SEO Specialist', description: 'Optimize websites for search engine rankings', location: 'Austin, TX', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['SEO Tools', 'Keyword Research', 'Technical SEO', 'Analytics'] },
      { title: 'Email Marketing Coordinator', description: 'Design and execute email marketing campaigns', location: 'Chicago, IL', jobType: 'full-time', category: 'Marketing', experienceLevel: 'entry', salary: { min: 45000, max: 60000 }, requirements: ['Email Marketing Platforms', 'HTML/CSS', 'A/B Testing', 'Analytics'] },
      { title: 'Brand Manager', description: 'Develop and maintain brand identity and strategy', location: 'San Francisco, CA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'senior', salary: { min: 95000, max: 125000 }, requirements: ['Brand Strategy', 'Market Research', 'Creative Direction', 'Project Management'] },
      { title: 'Marketing Analytics Manager', description: 'Analyze marketing performance and ROI', location: 'Seattle, WA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'senior', salary: { min: 90000, max: 120000 }, requirements: ['Marketing Analytics', 'SQL', 'Tableau', 'Statistical Analysis'] },
      { title: 'PPC Specialist', description: 'Manage pay-per-click advertising campaigns', location: 'Denver, CO', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 60000, max: 80000 }, requirements: ['Google Ads', 'Facebook Ads', 'PPC Management', 'Conversion Optimization'] },
      { title: 'Marketing Coordinator', description: 'Support marketing team with campaign execution', location: 'Miami, FL', jobType: 'full-time', category: 'Marketing', experienceLevel: 'entry', salary: { min: 40000, max: 55000 }, requirements: ['Marketing Support', 'Project Coordination', 'Communication Skills', 'Detail Oriented'] },
      { title: 'Growth Marketing Manager', description: 'Drive user acquisition and retention strategies', location: 'San Diego, CA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'senior', salary: { min: 100000, max: 130000 }, requirements: ['Growth Hacking', 'A/B Testing', 'User Analytics', 'Conversion Optimization'] },
      { title: 'Marketing Automation Specialist', description: 'Implement and manage marketing automation workflows', location: 'Boston, MA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 70000, max: 90000 }, requirements: ['Marketing Automation', 'CRM Systems', 'Lead Nurturing', 'Workflow Design'] },
      { title: 'Influencer Marketing Manager', description: 'Develop and execute influencer marketing campaigns', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['Influencer Relations', 'Campaign Management', 'Social Media', 'Negotiation'] },
      { title: 'Product Marketing Manager', description: 'Drive go-to-market strategy for products', location: 'Palo Alto, CA', jobType: 'full-time', category: 'Marketing', experienceLevel: 'senior', salary: { min: 110000, max: 140000 }, requirements: ['Product Marketing', 'Go-to-Market Strategy', 'Competitive Analysis', 'Messaging'] },
      { title: 'Event Marketing Coordinator', description: 'Plan and execute marketing events and trade shows', location: 'Las Vegas, NV', jobType: 'full-time', category: 'Marketing', experienceLevel: 'mid', salary: { min: 50000, max: 70000 }, requirements: ['Event Planning', 'Project Management', 'Vendor Relations', 'Budget Management'] },
      { title: 'Marketing Intern', description: 'Learn marketing fundamentals through hands-on experience', location: 'Remote', jobType: 'internship', category: 'Marketing', experienceLevel: 'entry', salary: { min: 15, max: 20 }, requirements: ['Marketing Student', 'Communication Skills', 'Social Media Knowledge', 'Eagerness to Learn'] },

      // Sales Jobs (15 jobs)
      { title: 'Sales Manager', description: 'Lead sales team and drive revenue growth', location: 'New York, NY', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 90000, max: 130000 }, requirements: ['Sales Leadership', 'Team Management', 'CRM Systems', 'Revenue Growth'] },
      { title: 'Account Executive', description: 'Manage client relationships and close deals', location: 'Chicago, IL', jobType: 'full-time', category: 'Sales', experienceLevel: 'mid', salary: { min: 70000, max: 100000 }, requirements: ['B2B Sales', 'Relationship Building', 'Negotiation', 'Salesforce'] },
      { title: 'Inside Sales Representative', description: 'Generate leads and close sales remotely', location: 'Remote', jobType: 'full-time', category: 'Sales', experienceLevel: 'entry', salary: { min: 45000, max: 65000 }, requirements: ['Phone Sales', 'Lead Generation', 'CRM', 'Communication Skills'] },
      { title: 'Business Development Manager', description: 'Identify and develop new business opportunities', location: 'San Francisco, CA', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 95000, max: 125000 }, requirements: ['Business Development', 'Strategic Partnerships', 'Market Analysis', 'Networking'] },
      { title: 'Sales Development Representative', description: 'Qualify leads and set appointments for sales team', location: 'Austin, TX', jobType: 'full-time', category: 'Sales', experienceLevel: 'entry', salary: { min: 50000, max: 70000 }, requirements: ['Lead Qualification', 'Prospecting', 'Cold Calling', 'Sales Tools'] },
      { title: 'Regional Sales Director', description: 'Oversee sales operations in assigned region', location: 'Dallas, TX', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 120000, max: 160000 }, requirements: ['Regional Management', 'Sales Strategy', 'Team Leadership', 'P&L Responsibility'] },
      { title: 'Customer Success Manager', description: 'Ensure customer satisfaction and retention', location: 'Seattle, WA', jobType: 'full-time', category: 'Sales', experienceLevel: 'mid', salary: { min: 75000, max: 95000 }, requirements: ['Customer Success', 'Account Management', 'Retention Strategies', 'Problem Solving'] },
      { title: 'Enterprise Sales Executive', description: 'Sell to large enterprise clients', location: 'Boston, MA', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 110000, max: 150000 }, requirements: ['Enterprise Sales', 'Complex Sales Cycles', 'Executive Relationships', 'Solution Selling'] },
      { title: 'Sales Operations Analyst', description: 'Analyze sales data and optimize processes', location: 'Denver, CO', jobType: 'full-time', category: 'Sales', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['Sales Analytics', 'Data Analysis', 'Process Improvement', 'Excel/SQL'] },
      { title: 'Channel Sales Manager', description: 'Manage partner and channel relationships', location: 'Atlanta, GA', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 85000, max: 115000 }, requirements: ['Channel Management', 'Partner Relations', 'Indirect Sales', 'Program Development'] },
      { title: 'Technical Sales Engineer', description: 'Provide technical expertise in sales process', location: 'San Jose, CA', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 105000, max: 135000 }, requirements: ['Technical Sales', 'Product Demos', 'Technical Knowledge', 'Solution Design'] },
      { title: 'Retail Sales Associate', description: 'Assist customers and drive store sales', location: 'Los Angeles, CA', jobType: 'part-time', category: 'Sales', experienceLevel: 'entry', salary: { min: 15, max: 18 }, requirements: ['Customer Service', 'Product Knowledge', 'Sales Skills', 'Team Player'] },
      { title: 'Sales Trainer', description: 'Train and develop sales team members', location: 'Phoenix, AZ', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 80000, max: 110000 }, requirements: ['Sales Training', 'Curriculum Development', 'Presentation Skills', 'Sales Experience'] },
      { title: 'Key Account Manager', description: 'Manage relationships with key strategic accounts', location: 'Miami, FL', jobType: 'full-time', category: 'Sales', experienceLevel: 'senior', salary: { min: 85000, max: 115000 }, requirements: ['Key Account Management', 'Strategic Planning', 'Relationship Building', 'Revenue Growth'] },
      { title: 'Sales Intern', description: 'Learn sales fundamentals and support sales team', location: 'Remote', jobType: 'internship', category: 'Sales', experienceLevel: 'entry', salary: { min: 15, max: 18 }, requirements: ['Business Student', 'Communication Skills', 'Eagerness to Learn', 'Professional Attitude'] },

      // Finance Jobs (10 jobs)
      { title: 'Financial Analyst', description: 'Analyze financial data and create reports', location: 'New York, NY', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 75000, max: 95000 }, requirements: ['Financial Analysis', 'Excel', 'Financial Modeling', 'CPA/CFA Preferred'] },
      { title: 'Senior Accountant', description: 'Manage accounting operations and financial reporting', location: 'Chicago, IL', jobType: 'full-time', category: 'Finance', experienceLevel: 'senior', salary: { min: 70000, max: 90000 }, requirements: ['Accounting', 'GAAP', 'Financial Reporting', 'CPA License'] },
      { title: 'Investment Banking Analyst', description: 'Support investment banking transactions and analysis', location: 'New York, NY', jobType: 'full-time', category: 'Finance', experienceLevel: 'entry', salary: { min: 85000, max: 110000 }, requirements: ['Finance Degree', 'Financial Modeling', 'Valuation', 'Excel/PowerPoint'] },
      { title: 'Corporate Finance Manager', description: 'Lead corporate finance initiatives and strategy', location: 'San Francisco, CA', jobType: 'full-time', category: 'Finance', experienceLevel: 'senior', salary: { min: 110000, max: 140000 }, requirements: ['Corporate Finance', 'M&A Experience', 'Financial Planning', 'MBA Preferred'] },
      { title: 'Tax Specialist', description: 'Prepare and review tax returns and compliance', location: 'Dallas, TX', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 60000, max: 80000 }, requirements: ['Tax Preparation', 'Tax Software', 'Tax Law Knowledge', 'CPA Preferred'] },
      { title: 'Budget Analyst', description: 'Develop and monitor organizational budgets', location: 'Washington, DC', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['Budget Planning', 'Financial Analysis', 'Forecasting', 'Government Experience'] },
      { title: 'Risk Management Analyst', description: 'Assess and mitigate financial risks', location: 'Boston, MA', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 80000, max: 100000 }, requirements: ['Risk Assessment', 'Financial Modeling', 'Regulatory Knowledge', 'Analytics'] },
      { title: 'Treasury Analyst', description: 'Manage cash flow and treasury operations', location: 'Atlanta, GA', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 70000, max: 90000 }, requirements: ['Treasury Management', 'Cash Flow Analysis', 'Banking Relations', 'Finance Degree'] },
      { title: 'Financial Planning Analyst', description: 'Support financial planning and forecasting', location: 'Denver, CO', jobType: 'full-time', category: 'Finance', experienceLevel: 'mid', salary: { min: 68000, max: 88000 }, requirements: ['Financial Planning', 'Forecasting', 'Budgeting', 'Advanced Excel'] },
      { title: 'Accounts Payable Specialist', description: 'Process invoices and manage vendor payments', location: 'Phoenix, AZ', jobType: 'full-time', category: 'Finance', experienceLevel: 'entry', salary: { min: 40000, max: 55000 }, requirements: ['Accounts Payable', 'Data Entry', 'Attention to Detail', 'ERP Systems'] },

      // Healthcare Jobs (10 jobs)
      { title: 'Registered Nurse', description: 'Provide patient care in hospital setting', location: 'Houston, TX', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['RN License', 'Patient Care', 'Medical Knowledge', 'Communication Skills'] },
      { title: 'Medical Assistant', description: 'Support physicians with patient care and administrative tasks', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'entry', salary: { min: 35000, max: 45000 }, requirements: ['Medical Assistant Certification', 'Patient Care', 'Medical Terminology', 'Administrative Skills'] },
      { title: 'Physical Therapist', description: 'Help patients recover from injuries and improve mobility', location: 'Miami, FL', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'mid', salary: { min: 75000, max: 95000 }, requirements: ['PT License', 'Rehabilitation', 'Patient Assessment', 'Treatment Planning'] },
      { title: 'Healthcare Data Analyst', description: 'Analyze healthcare data to improve patient outcomes', location: 'Boston, MA', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'mid', salary: { min: 70000, max: 90000 }, requirements: ['Healthcare Analytics', 'SQL', 'Statistical Analysis', 'HIPAA Knowledge'] },
      { title: 'Medical Coder', description: 'Assign medical codes for billing and insurance purposes', location: 'Remote', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'entry', salary: { min: 40000, max: 55000 }, requirements: ['Medical Coding Certification', 'ICD-10', 'CPT Codes', 'Attention to Detail'] },
      { title: 'Pharmacy Technician', description: 'Assist pharmacists with medication preparation and dispensing', location: 'Chicago, IL', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'entry', salary: { min: 32000, max: 42000 }, requirements: ['Pharmacy Tech Certification', 'Medication Knowledge', 'Customer Service', 'Accuracy'] },
      { title: 'Clinical Research Coordinator', description: 'Coordinate clinical trials and research studies', location: 'San Diego, CA', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'mid', salary: { min: 55000, max: 75000 }, requirements: ['Clinical Research', 'GCP Knowledge', 'Data Collection', 'Regulatory Compliance'] },
      { title: 'Healthcare Administrator', description: 'Manage healthcare facility operations and staff', location: 'Atlanta, GA', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'senior', salary: { min: 80000, max: 110000 }, requirements: ['Healthcare Administration', 'Leadership', 'Budget Management', 'Regulatory Knowledge'] },
      { title: 'Medical Device Sales Rep', description: 'Sell medical devices to healthcare providers', location: 'Dallas, TX', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'mid', salary: { min: 70000, max: 100000 }, requirements: ['Medical Device Knowledge', 'B2B Sales', 'Healthcare Relationships', 'Technical Aptitude'] },
      { title: 'Health Information Technician', description: 'Manage patient health information and medical records', location: 'Seattle, WA', jobType: 'full-time', category: 'Healthcare', experienceLevel: 'entry', salary: { min: 38000, max: 50000 }, requirements: ['Health Information Management', 'EHR Systems', 'HIPAA Compliance', 'Data Entry'] },

      // Education Jobs (10 jobs)
      { title: 'Elementary School Teacher', description: 'Teach elementary students core subjects', location: 'Denver, CO', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 45000, max: 65000 }, requirements: ['Teaching License', 'Elementary Education', 'Classroom Management', 'Curriculum Development'] },
      { title: 'High School Math Teacher', description: 'Teach mathematics to high school students', location: 'Austin, TX', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 50000, max: 70000 }, requirements: ['Math Teaching License', 'Mathematics Degree', 'Lesson Planning', 'Student Assessment'] },
      { title: 'Special Education Teacher', description: 'Provide specialized instruction to students with disabilities', location: 'Portland, OR', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 48000, max: 68000 }, requirements: ['Special Education License', 'IEP Development', 'Behavioral Management', 'Adaptive Teaching'] },
      { title: 'School Counselor', description: 'Provide academic and personal counseling to students', location: 'Phoenix, AZ', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 50000, max: 70000 }, requirements: ['Counseling License', 'Student Development', 'Crisis Intervention', 'College Planning'] },
      { title: 'Instructional Designer', description: 'Design and develop educational curricula and materials', location: 'Remote', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 65000, max: 85000 }, requirements: ['Instructional Design', 'E-learning Tools', 'Curriculum Development', 'Educational Technology'] },
      { title: 'University Professor', description: 'Teach and conduct research at university level', location: 'Boston, MA', jobType: 'full-time', category: 'Education', experienceLevel: 'senior', salary: { min: 70000, max: 120000 }, requirements: ['PhD', 'Research Experience', 'Teaching Experience', 'Publications'] },
      { title: 'ESL Teacher', description: 'Teach English as a Second Language to non-native speakers', location: 'Los Angeles, CA', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 45000, max: 60000 }, requirements: ['ESL Certification', 'TESOL/TEFL', 'Cultural Sensitivity', 'Language Teaching'] },
      { title: 'Educational Technology Specialist', description: 'Support technology integration in educational settings', location: 'San Francisco, CA', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 60000, max: 80000 }, requirements: ['Educational Technology', 'IT Support', 'Training', 'Learning Management Systems'] },
      { title: 'Academic Advisor', description: 'Guide students in academic planning and career development', location: 'Minneapolis, MN', jobType: 'full-time', category: 'Education', experienceLevel: 'mid', salary: { min: 45000, max: 60000 }, requirements: ['Academic Advising', 'Student Services', 'Degree Planning', 'Communication Skills'] },
      { title: 'Substitute Teacher', description: 'Provide temporary instruction when regular teachers are absent', location: 'Tampa, FL', jobType: 'part-time', category: 'Education', experienceLevel: 'entry', salary: { min: 15, max: 25 }, requirements: ['Teaching Substitute License', 'Classroom Management', 'Adaptability', 'Subject Knowledge'] }
    ];

    // Clear existing jobs to avoid duplicates
    await Job.deleteMany({});
    console.log('Cleared existing jobs');

    // Add all jobs
    for (const jobData of jobs) {
      const job = new Job({
        ...jobData,
        company: systemUser._id,
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) // 30 days from now
      });
      await job.save();
      console.log(`Added: ${jobData.title}`);
    }

    console.log(`Successfully seeded ${jobs.length} jobs!`);
    mongoose.connection.close();
  } catch (error) {
    console.error('Seeding failed:', error);
    mongoose.connection.close();
  }
};

seed100Jobs();